/**
 * Emits `dist/sw.js` after a Vite build.
 *
 * Two things here look like implementation detail and are not:
 *
 * The precache list comes from walking `dist/`, NOT from `.vite/manifest.json`. That
 * manifest is not even emitted without `build.manifest`, and when it is, its only
 * entry maps `"index.html"` to the JS chunk — `index.html` itself is absent, and
 * everything copied from `public/` (the webmanifest, the icons) is absent by
 * construction. A manifest-derived list would precache 2 of 7 files and quietly miss
 * the one file the whole "precache as a unit" guarantee is named after.
 *
 * The build id hashes file CONTENTS, not names. `index.html` is not in the JS module
 * graph, so editing it changes no hashed filename; a name-derived id would leave
 * `sw.js` byte-identical, the browser would see no update, and the new `index.html`
 * would never reach the device. The CSP lives in `index.html`.
 */

import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const DEFAULT_BASE = '/wedding/'

function walk(dir, found = []) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name)
    if (statSync(path).isDirectory()) walk(path, found)
    else found.push(path)
  }
  return found
}

/**
 * Files that must never be precached, whatever a local `public/` happens to hold.
 *
 * `sw.js` is the worker itself. `__dev-board.json` is the board fixture `scripts/drive.mjs` reads
 * (see its header): it is gitignored, so CI never sees it and the DEPLOYED worker was never at
 * risk — but anyone who has driven the app locally has one sitting in `public/`, and `vite build`
 * copies it straight into `dist/`, where this walk would list it and the worker would precache
 * somebody's fixture board for offline use. The `__` prefix is the convention; anything wearing it
 * is a local artefact.
 */
const NEVER_PRECACHED = (path) => path === 'sw.js' || path.startsWith('__')

/** Every file in the tree except the worker itself and any local artefact, as forward-slash paths. */
export function precachePaths(distDir) {
  return walk(distDir)
    .map((path) => relative(distDir, path).split(sep).join('/'))
    .filter((path) => !NEVER_PRECACHED(path))
    .sort()
}

function renderServiceWorker({ paths, base, buildId }) {
  const assets = JSON.stringify(
    paths.map((path) => base + path),
    null,
    2,
  )

  return `/* Generated by scripts/build-sw.js. Do not edit. */
const CACHE = 'wd-${buildId}'
const BASE = '${base}'
const INDEX = BASE + 'index.html'
const ASSETS = ${assets}

self.addEventListener('install', (event) => {
  // cache:'reload' bypasses the HTTP cache. GitHub Pages serves max-age=600 on every
  // object through a CDN, so without this, install can pair a fresh sw.js with an
  // edge-cached stale index.html and precache a mismatched set.
  //
  // addAll rejecting is the safety mechanism, not a nuisance: a missing hashed asset
  // 404s, install fails, this worker never activates, and the previous one keeps
  // serving a version that is at least complete.
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(ASSETS.map((url) => new Request(url, { cache: 'reload' })))),
  )
  // Deliberately no skipWaiting: a running page keeps the version it started with.
  // src/lib/serviceWorker.js decides when a swap is safe.
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))),
      ),
  )
})

self.addEventListener('fetch', (event) => {
  // First, and not inside an async function: scope decides which CLIENTS this worker
  // controls, not which requests it sees, so the Apps Script endpoint arrives here
  // too. It must be left entirely alone — a worker responding to it would be an
  // un-CSP'd proxy in front of the edit key (a <meta> CSP does not cover a worker,
  // and Pages sends no header), and even a pass-through fetch can change how the
  // Apps Script 302 is followed.
  if (new URL(event.request.url).origin !== self.location.origin) return
  if (event.request.method !== 'GET') return

  // A start_url launch requests BASE itself, but the precached key is
  // BASE + 'index.html', so matching the request would miss.
  //
  // ignoreVary because caches.match honours Vary by default and the servers involved
  // set it: GitHub Pages sends 'Vary: Accept-Encoding', vite preview sends
  // 'Vary: Origin'. A header difference between the precache fetch and the page's own
  // request would then miss and fall through to the network, which offline means
  // failing — a cache that silently only works online. These are content-hashed
  // immutable files, so the URL is the only key that matters.
  if (event.request.mode === 'navigate') {
    event.respondWith(
      caches.match(INDEX, { ignoreVary: true }).then((hit) => hit || fetch(event.request)),
    )
    return
  }

  event.respondWith(
    caches.match(event.request, { ignoreVary: true }).then((hit) => hit || fetch(event.request)),
  )
})

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
})
`
}

export function buildFromDist(distDir, base) {
  const paths = precachePaths(distDir)
  const hash = createHash('sha256')
  for (const path of paths) {
    hash.update(path)
    hash.update(readFileSync(join(distDir, path)))
  }
  return {
    paths,
    source: renderServiceWorker({ paths, base, buildId: hash.digest('hex').slice(0, 12) }),
  }
}

// Only when run as a script, so the test can import the builder without writing.
if (process.argv[1] && process.argv[1] === fileURLToPath(import.meta.url)) {
  const base = process.env.VITE_BASE ?? DEFAULT_BASE
  const { paths, source } = buildFromDist('dist', base)
  writeFileSync(join('dist', 'sw.js'), source)
  console.log(`sw.js: ${paths.length} files precached under ${base}`)
}
